### ISSUE TITLE
Signature was not found in module lsasrv.dll 

### ISSUE THREAD

**Issue by greckko** [skelsec/pypykatz#15]
Hello I'm getting the following error when running pypykatz live lsa

Exception: Signature was not found in module lsasrv.dll Signature: 33ff458937488bf34585c974

==== Parsing errors:
live

**Comment by skelsec** [comment]
Hello welcome to GitHub.

Can you please dump the lsass.exe and upload it to the URL specified in the readme (preferred) OR/AND give detailed description on the issue?
OS name:
CPU architecture:
Buildnumber:
Minorversison:
Majorversion:
msv.dll timestamp:

Thx!

**Comment by skelsec** [comment]
Actually nevermind, I found the problem, will fix it in the next version

**Comment by n00py** [comment]
What was the fix?  I am having the same issue.  

Exception: Signature was not found in module lsasrv.dll Signature: 33ff458937488bf34585c974

**Comment by skelsec** [comment]
The fix was to update the linked list entry point signatures to support the newer windows 10 builds.
It is shipped in the latest version, even in pip since a few days now.

I'd propose to update your pypykatz.
OFC if the issue still persists then pls create a new issue and pls pls pls give test data bc it's a really tiresome work to hunt down the correct buildnumber that matches yours.

**Comment by n00py** [comment]
Yeah I just tried this morning when installing with pip.  Sadly in this case I can't give the test data because it's my own box but it I can recreate on another device I'll send you the lsass dump.

**Comment by skelsec** [comment]
@n00py any update on this?
