### ISSUE TITLE
LSA signature not found

### ISSUE THREAD

**Issue by forensenellanebbia** [skelsec/pypykatz#20]
**Error details**
File type: memory dump from a public ENISA training [exercise](https://www.enisa.europa.eu/topics/trainings-for-cybersecurity-specialists/online-training-material/technical-operational#Forensic_analysis_Local_Incident_Response)). I uploaded the file (1,42 GB) to here:
https://www.dropbox.com/s/m4djwnnym06j8pa/memory_win10_10586.zip?dl=0
Error: 

> (rekall) ubuntu@vmubuntudskt:~$ pypykatz rekall '/home/ubuntu/Desktop/memory.img' 
> INFO:pypykatz:Searching LSASS process
> INFO:pypykatz:Detected kernel base at 0x8226D000
> INFO:pypykatz:WARNING! msv.dll timestamp not found! This could cause errors with older windows builds. You might need to specify it manually for anti_mimikatz structs!
> INFO:pypykatz:module.start_addr 1941110784
> WARNING:root:signature not found! 6a026a1068
> Traceback (most recent call last):
>   File "/home/ubuntu/rekall/bin/pypykatz", line 11, in <module>
>     load_entry_point('pypykatz', 'console_scripts', 'pypykatz')()
>   File "/home/ubuntu/pypykatz/pypykatz/__main__.py", line 86, in main
>     mimi = pypykatz.parse_memory_dump_rekall(args.memoryfile, args.timestamp_override)
>   File "/home/ubuntu/pypykatz/pypykatz/pypykatz.py", line 65, in parse_memory_dump_rekall
>     mimi.start()
>   File "/home/ubuntu/pypykatz/pypykatz/pypykatz.py", line 168, in start
>     self.lsa_decryptor = self.get_lsa()
>   File "/home/ubuntu/pypykatz/pypykatz/pypykatz.py", line 98, in get_lsa
>     lsa_dec = LsaDecryptor(self.reader, lsa_dec_template, self.sysinfo)
>   File "/home/ubuntu/pypykatz/pypykatz/lsadecryptor/lsa_decryptor.py", line 21, in __init__
>     self.acquire_crypto_material()
>   File "/home/ubuntu/pypykatz/pypykatz/lsadecryptor/lsa_decryptor.py", line 25, in acquire_crypto_material
>     sigpos = self.find_signature()
>   File "/home/ubuntu/pypykatz/pypykatz/lsadecryptor/lsa_decryptor.py", line 46, in find_signature
>     raise Exception('LSA signature not found!')
> Exception: LSA signature not found!

**Operating system details** _(found with Rekall)_
OS name: Windows 10
OS version: 10586.th2_release_sec.160630-1736
CPU architecture: x86
msv1_0.dll timestamp: 2016:03:29 06:46:29Z

**Pypykatz installation**
Pypykatz installed through git clone on Ubuntu 18.04.2 with Python 3.6.7. Pypykatz and Rekall have been installed in the same virtualenv.

Thanks!

**Comment by skelsec** [comment]
I don't really know what type of memdump this is, given that the pslist returns weird characters and lsass.exe full memory dump is 7Mb only.
Problem is: for 32 bit windows 10 systems there is only 1 LSA signature, and that one doesn't exist in this dump. Without LSA signature there is no point in continuing because decryption keys will be missing (maybe for forensics purposes there would be a benefit of providing logon session info etc without the credentials, but this is something I don't have time atm)

I verified it manually, and cannot find the signature bytes, so I suspect it's the problem with the memory image.

PS: this is the second unsolved issue I encountered with 32 bit dumps
