### ISSUE TITLE
Error "signature not found!" - lsass dmp linked

### ISSUE THREAD

**Issue by WaiZ0** [skelsec/pypykatz#49]
Hi,
While dumping the lsass process with lsassy I encountered a signature error as it was not found.
So I dump the lsass localy to give it to you in case you want to implement it ! :) 

**Here is the build of the remote server:**
![image](https://user-images.githubusercontent.com/33723878/78296215-9d39a400-752d-11ea-9b01-58fdeaa6121a.png)

**Here is the error:**
![image](https://user-images.githubusercontent.com/33723878/78296283-b7738200-752d-11ea-8cec-7076babb90cc.png)

**And here is the lsass dump:**
[lsass_pypykatz.zip](https://github.com/skelsec/pypykatz/files/4423338/lsass_pypykatz.zip)

Thank you for your awesome work, I hope this will be usefull :D

**Comment by skelsec** [comment]
Thank you for your contribution, however the current version parses the file you submitted correctly.
The exception and warning messages are normal operation in the current version, and it will halt completely if absolutely no signature can be found.  
In case anyone interested as on why this is normal: the signatures are not always corresponding to buildversion/majdorversion info therefore some guessing must be done to support more versions rather than only hardcode the buildversion-signature pairs which will render some dumps unparsable.

**Comment by WaiZ0** [comment]
Oh I see, so the signature expected to be found, with some "fingerprinting" I guess, are not found therefore you try with other signature, thank you for letting me know ! 
Should I close the case or let it be for other people with the same situation ?
