### ISSUE TITLE
Instructions for the new features missing?

### ISSUE THREAD

**Issue by jsdhasfeds** [skelsec/pypykatz#78]
Hi,

Thank you for your work! I would very much like to try the new features in version 0.4.8 such as DCSync and remote LSASS dumping. However, it seems the Wiki is not yet updated. The built-in help also seem to be missing info about the new features. Am I missing something?

**Comment by skelsec** [comment]
Hello,
Yeah, I haven't been updating wiki much lately due to lack of time. However, the new features do have a nice help menu you can obtain by typing `pypykatz smb -h` and then progressing with `pypykatz smb lsassdump -h` etc. Additionally you can find the manu code here for all SMB related functions: https://github.com/skelsec/pypykatz/blob/master/pypykatz/smb/cmdhelper.py

**Comment by skelsec** [comment]
Use the current `master` branch or numbered version `0.5.0` and see the [wiki](https://github.com/skelsec/pypykatz/wiki). Everything is now documented.
